# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-22 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentManager',
        ),
        migrations.DeleteModel(
            name='SnippetManager',
        ),
        migrations.DeleteModel(
            name='UserManager',
        ),
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.IntegerField(default=1),
        ),
    ]
